name: Comment link on PR

on:
  workflow_run:
    workflows: ['upload-artifact']
    type: [completed]

jobs: 
  artifact-comment:
    runs-on: ubuntu-latest
    # if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:

      - name: Get artifact from previous workflow
        uses: actions/github-script@v5
        id: getArtifact
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const run_id = ${{github.event.workflow_run.id}};
            const {owner, repo} = context.repo;

            github.rest.actions.listWorkflowRunArtifacts, {owner, repo, run_id});
            for (const artifact of artifacts) {
              console.log(artifact.name)
              console.log(artifact.id)
            }
          debug: true

      # - run: echo "${{steps.getaArtifact.outputs.result.artifacts[0].archive_download_url}}"
      # - run: echo "${{steps.getaArtifact.outputs.result}}"