name: Taqueria build and upload

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build_taqueria:

    runs-on: ubuntu-latest

    steps:

      - name: Get Workflow Info
        uses: actions/github-script@v5
        id: gatherInfo
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context)
            console.log(context.repo.owner)
            console.log(context.repo.repo)
            console.log(context.runId)
      
      - name: Build taqueria
        run: |
          echo "Try github_run_id variable $GITHUB_RUN_ID" > test.txt

      - name: Upload Taqueria Binary 
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: taqueria
          path: ./test.txt
          retention-days: 1

  artifact-comment:

    needs: build_taqueria
    runs-on: ubuntu-latest

    steps:

      - name: Get Workflow Info
        uses: actions/github-script@v5
        id: gatherInfo
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context)
            console.log(context.repo.owner)
            console.log(context.repo.repo)
            console.log(context.runId)

      - name: Get artifact from previous step
        uses: actions/github-script@v5
        id: getArtifact
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: 1668913690
            });
          debug: true

      # - run: echo "${{steps.getaArtifact.outputs.result.artifacts[0].archive_download_url}}"
      - run: echo "${{steps.getaArtifact.outputs.result}}"