name: upload-artifact

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build_taqueria:

    runs-on: ubuntu-latest

    steps:
      
      - name: Build taqueria
        run: |
          echo "Try github_run_id variable $GITHUB_RUN_ID" > test.txt

      - name: Upload Taqueria Binary 
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: taqueria
          path: ./test.txt
          retention-days: 1

      - name: Get artifact from previous workflow
        uses: actions/github-script@v5
        id: getArtifact
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const run_id = 1669239715;
            const {owner, repo} = context.repo;

            github.rest.actions.listWorkflowRunArtifacts, {owner, repo, run_id});
            for (const artifact of artifacts) {
              console.log(artifact.name)
              console.log(artifact.id)
            }
          debug: true